version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: app
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - ./:/app
    env_file: .env
    # networks:
    #   - dev

  postgres:
    image: postgres
    container_name: billing_db
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - go_volume:/var/lib/postgresql
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    # networks:
    #   - dev

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    # networks:
    #   - dev

volumes:
  go_volume:

networks:
  dev:
    name: dev
  test:
    name: test