// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/operations/repo.go

// Package operations is a generated GoMock package.
package operations

import (
	context "context"
	sql "database/sql"
	gomock "github.com/golang/mock/gomock"
	decimal "github.com/shopspring/decimal"
	reflect "reflect"
)

// MockOperationsManager is a mock of OperationsManager interface
type MockOperationsManager struct {
	ctrl     *gomock.Controller
	recorder *MockOperationsManagerMockRecorder
}

// MockOperationsManagerMockRecorder is the mock recorder for MockOperationsManager
type MockOperationsManagerMockRecorder struct {
	mock *MockOperationsManager
}

// NewMockOperationsManager creates a new mock instance
func NewMockOperationsManager(ctrl *gomock.Controller) *MockOperationsManager {
	mock := &MockOperationsManager{ctrl: ctrl}
	mock.recorder = &MockOperationsManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockOperationsManager) EXPECT() *MockOperationsManagerMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockOperationsManager) Create(ctx context.Context, tx *sql.Tx, operation string, walletFrom, walletTo int, amount decimal.Decimal) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, operation, walletFrom, walletTo, amount)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockOperationsManagerMockRecorder) Create(ctx, tx, operation, walletFrom, walletTo, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOperationsManager)(nil).Create), ctx, tx, operation, walletFrom, walletTo, amount)
}

// List mocks base method
func (m *MockOperationsManager) List(ctx context.Context, params *ListParams) (*sql.Rows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].(*sql.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockOperationsManagerMockRecorder) List(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOperationsManager)(nil).List), ctx, params)
}
