// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/operations/pipes.go

// Package operations is a generated GoMock package.
package operations

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIOperationsProcessor is a mock of IOperationsProcessor interface
type MockIOperationsProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockIOperationsProcessorMockRecorder
}

// MockIOperationsProcessorMockRecorder is the mock recorder for MockIOperationsProcessor
type MockIOperationsProcessorMockRecorder struct {
	mock *MockIOperationsProcessor
}

// NewMockIOperationsProcessor creates a new mock instance
func NewMockIOperationsProcessor(ctrl *gomock.Controller) *MockIOperationsProcessor {
	mock := &MockIOperationsProcessor{ctrl: ctrl}
	mock.recorder = &MockIOperationsProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIOperationsProcessor) EXPECT() *MockIOperationsProcessorMockRecorder {
	return m.recorder
}

// Process mocks base method
func (m *MockIOperationsProcessor) Process(ctx context.Context, or OperationsManager, listParams *ListParams, marshaller IFileMarshaller) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, or, listParams, marshaller)
	ret0, _ := ret[0].(error)
	return ret0
}

// Process indicates an expected call of Process
func (mr *MockIOperationsProcessorMockRecorder) Process(ctx, or, listParams, marshaller interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockIOperationsProcessor)(nil).Process), ctx, or, listParams, marshaller)
}
