basePath: /
definitions:
  users.EnrollForm:
    properties:
      amount:
        type: number
    required:
    - amount
    type: object
  users.UserForm:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  users.UserSerializer:
    properties:
      balance:
        type: number
      currency:
        type: string
      email:
        type: string
      id:
        type: integer
    type: object
  utils.ErrorMsg:
    properties:
      message:
        type: string
    type: object
  utils.FormErrorSerializer:
    properties:
      messages:
        additionalProperties:
          items:
            type: string
          type: array
        type: object
    type: object
  wallets.WalletForm:
    properties:
      amount:
        type: number
      wallet_from:
        type: integer
      wallet_to:
        type: integer
    required:
    - amount
    - wallet_from
    - wallet_to
    type: object
  wallets.walletSerializer:
    properties:
      wallet_from:
        type: integer
    type: object
host: localhost:8000
info:
  contact: {}
  description: Simple billing system
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Billing System API
  version: "1.0"
paths:
  /api/operations/:
    get:
      consumes:
      - application/json
      description: Get wallet operations logs
      parameters:
      - description: Report format
        in: query
        name: format
        type: string
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of items per page
        in: query
        name: per_page
        type: integer
      produces:
      - application/octet-stream
      summary: Wallet operations
      tags:
      - operations
  /api/users/:
    post:
      consumes:
      - application/json
      description: Create new user and wallet
      parameters:
      - description: User attributes
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/users.UserForm'
      produces:
      - application/json
      responses:
        "201":
          description: Create user response
          schema:
            $ref: '#/definitions/users.UserSerializer'
        "400":
          description: User form validation error
          schema:
            $ref: '#/definitions/utils.FormErrorSerializer'
        default:
          description: ""
          schema:
            $ref: '#/definitions/utils.ErrorMsg'
      summary: Create new user
      tags:
      - users
  /api/users/{id}/enroll/:
    post:
      consumes:
      - application/json
      description: Enroll particular users wallet
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: Enrollment attributes
        in: body
        name: enroll
        required: true
        schema:
          $ref: '#/definitions/users.EnrollForm'
      produces:
      - application/json
      responses:
        "200":
          description: Retrieving user information with updated balance
          schema:
            $ref: '#/definitions/users.UserSerializer'
        "400":
          description: Enroll form validation error
          schema:
            $ref: '#/definitions/utils.FormErrorSerializer'
        default:
          description: ""
          schema:
            $ref: '#/definitions/utils.ErrorMsg'
      summary: Enroll wallet
      tags:
      - users
  /api/wallets/transfer/:
    post:
      consumes:
      - application/json
      description: Transfer funds between two users
      parameters:
      - description: Transfer parameters
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/wallets.WalletForm'
      produces:
      - application/json
      responses:
        "200":
          description: Wallet from id
          schema:
            $ref: '#/definitions/wallets.walletSerializer'
        "400":
          description: Wallet transfer validation error
          schema:
            $ref: '#/definitions/utils.FormErrorSerializer'
        default:
          description: ""
          schema:
            $ref: '#/definitions/utils.ErrorMsg'
      summary: Transfer funds
      tags:
      - wallets
swagger: "2.0"
